#!/bin/bash --

# This general RetroArch template assumes roms are stored in
# XDG_DATA_HOME/game/<system> and the cores in XDG_DATA_HOME/retroarch/core.
rom=

# Append any configurations here, such as different controller layouts, filter
# options or otherwise. The configuration file is assumed to be in
# XDG_CONFIG_HOME/retroarch. Leave blank if unwanted.
append=

# Path to the games for a certain system, for example PSX:
romdir=${XDG_DATA_HOME:-$HOME/.local/share}/game/psx

# Location of RetroArch cores:
coredir=${XDG_DATA_HOME:-$HOME/.local/share}/retroarch/core

# Prefered core associated with the system:
emulator=$coredir/pcsx_rearmed_libretro.so

# For mesa, if needed, disable vsync:
export vblank_mode=0

if [[ $append ]]; then
    options=(--appendconfig "${XDG_CONFIG_HOME:-$HOME/.config}"/retroarch/"$append")
fi

exec retroarch "${options[@]}" -L "$emulator" "$romdir"/"$rom"
